### ISSUE TITLE
"from" CLI parameter

### ISSUE THREAD

**Issue by Mat001** [trp07/messages#14]
I noticed that there are two versions of --from parameter.
1. CLI param
2. in config file

Configuration function saves the actual "from" email address specified when config file is created (ie messages email -C)
Then there is --from as a parameter when sending an email via CLI.

The two can differ, for example if I specify "--from" in CLI when sending a message and set it to be different that actual "from" in the config file.

Let's say that my address in config is xxx@xxx.com.
Then I do `messages email -t 'yyy@yyy.com' -s 'TestSubject' -m 'test' -f 'SOMEOTHEREMAIL@test.com' -P 'someprofile'`

If I output both `from` I will see:
1. from config: zzz@xxx.com
2. from CLI param: SOMEOTHEREMAIL@test.com

The `--from` flag in the CLI basically allows overlay of the `from` in the config. It doesn't overwrite the config one, but its use is ambiguous.

I wonder what the purpose of the `--from` in the CLI is if we already have `from` that resides in config file.

**Comment by trp07** [comment]
You do have the option of using the --from option without using the -P option.  Afterwards a password prompt will for you to enter your password.  Suppose you didn't want to save that particular from-address in your config file.  In your example above, leave out the ``-P 'someprofile'`` part, and it should work just fine.
