### ISSUE TITLE
Text (Twilio) empty body and attachment

### ISSUE THREAD

**Issue by Mat001** [trp07/messages#20]
Problem:
In texting, when sending empty body without attachment, error is returned requesting for the body to not be empty.
In same case but with added attachment, no error is returned, and the message is sent successfully.

In both cases error about message body is empty should be raised.
Presence of an attachment somehow lets empty body get away with it.

(messages-Wx2T_w3C) m@m:~/repositories/messages$ messages twilio mtwilio '' -t '+14159999999' --verbose
Debugging info
2018-Nov-27 11:43:42 Message created.
400 Client Error: BAD REQUEST for url: https://api.twilio.com/2010-04-01/Accounts/ACc913350ac52ac36eb8add8a67a3836ad/Messages.json
Message body is required.

(messages-Wx2T_w3C) m@m:~/repositories/messages$ messages twilio mtwilio '' -t '+14159999999' -a 'https://imgs.xkcd.com/comics/python.png' --verbose
Debugging info
2018-Nov-27 11:43:53 Message created.
2018-Nov-27 11:43:53 Twilio info: 
 * From: +15105138811
 * To: ['+14159999999']
 * Body: ''
 * Attachments: ['https://imgs.xkcd.com/comics/python.png']
 * SID: None 
 * HTTP status code: 201
Message sent.

**Comment by trp07** [comment]
Business logic for text messages should imply one can send a text message with either:
1) A body message and no attachment
2) No body message with an attachment
3) A body message and an attachment

So, not receiving an error when sending a text with an attachment with no body message is in line with that logic, see #2 in the list above.

Perhaps what needs to be done instead, is change the error message to be something like, **Message body or attachment required.  Cannot send an empty message.**
