### ISSUE TITLE
Attribute Error while importing

### ISSUE THREAD

**Issue by kiurem66** [trp07/messages#26]
Python 3.8.5 (default, Jul 28 2020, 12:59:40)                                                                           [GCC 9.3.0] on linux                                                                                                    Type "help", "copyright", "credits" or "license" for more information.                                                  >>> from messages import Email                                                                                          Traceback (most recent call last):                                                                                        File "<stdin>", line 1, in <module>                                                                                     File "/usr/local/lib/python3.8/dist-packages/messages/__init__.py", line 7, in <module>                                   from .api import send                                                                                                 File "/usr/local/lib/python3.8/dist-packages/messages/api.py", line 3, in <module>                                        from .email_ import Email                                                                                             File "/usr/local/lib/python3.8/dist-packages/messages/email_.py", line 15, in <module>                                    from ._config import check_config_file                                                                                File "/usr/local/lib/python3.8/dist-packages/messages/_config.py", line 12, in <module>                                   import jsonconfig                                                                                                     File "/usr/local/lib/python3.8/dist-packages/jsonconfig/__init__.py", line 7, in <module>                                 from .core import Config                                                                                              File "/usr/local/lib/python3.8/dist-packages/jsonconfig/core.py", line 11, in <module>                                    from .jsonutils import to_json_file, from_json_file                                                                   File "/usr/local/lib/python3.8/dist-packages/jsonconfig/jsonutils.py", line 29, in <module>                               to_json = box._to_json                                                                                              AttributeError: module 'box' has no attribute '_to_json'

**Comment by trp07** [comment]
Good evening. Sorry for the late reply.  I'm looking into this.  It appears to be a problem with the `jsonconfig` dependency.  I created a similar issue at that repo.

**Comment by trp07** [comment]
I issued a PR to fix the bug in `jsonconfig`.  See https://github.com/json-transformations/jsonconfig/issues/218

Once merged, then updating the dependency should resolve the issue.

**Comment by trp07** [comment]
Fixed with version 0.7.0, uploaded to PyPI.
