### ISSUE TITLE
In README include a simple email & twitter tutorial to get the user up and running fast

### ISSUE THREAD

**Issue by bpeterso2000** [trp07/messages#4]
The README should contain a very simple email & twitter tutorial to get the user up and running fast.  The information should be copy & paste.

For example, use the `--configure` option so they can interactively populate it with their real info instead of dummy data.  This will give them a real-world working example so they can see it do something.

Maybe also provide hints for default settings for common email services.

**Comment by trp07** [comment]
good idea.  I plan to redo it in markdown, as well, since PyPI now supports REAME.md

**Comment by trp07** [comment]
I put in another example, not sure if more should be in there.  Instead I refer the users to the Wiki to see more examples.
