### ISSUE TITLE
Change README.rst to README.md

### ISSUE THREAD

**Issue by trp07** [trp07/messages#5]
Since PyPI now accepts README files written in markdown, I'd like to have this switched over.

**Comment by sclickk** [comment]
Okey dokey!

**Comment by trp07** [comment]
Hey, thanks for the quick turn around on this.  I'll take a look at your PR a little later today!

**Comment by trp07** [comment]
Completed.  Reference: https://github.com/trp07/messages/pull/6
Thanks, @sclickk!
